### ISSUE TITLE
setCreationIds (and therefore things like .getInfo) Errors uncleanly on files with no creationIDs set 

### ISSUE THREAD

**Issue by MP70** [singerla/pptx-automizer#80]
Even with useCreationIds: false,

Can we make it cleaner by either 
- A) not running if useCreationIds is false
- B) catch the error nicely
- C) Is it at all possible to just names in case of useCreationIds: false? (I'm looking at my getTextIds helper and that is what I did there.
-- added debug here 
```ts
  async getCreationIds(): Promise<SlideInfo[]> {
    const archive = this.archive;
    const relationships = await XmlHelper.getTargetsByRelationshipType(
      archive,
      this.path,
      this.relType,
    );
  
    const creationIds: SlideInfo[] = [];
    for (const slideRel of relationships) {
      try {
        const slideXml = await XmlHelper.getXmlFromArchive(
          archive,
          'ppt/' + slideRel.file,
        );
        
        if (!slideXml) {
          console.warn(`slideXml is undefined for file ${slideRel.file}`);
          continue;
        }
  
        const creationIdItem = slideXml.getElementsByTagName('p14:creationId').item(0);
  
        if (!creationIdItem) {
          console.warn(`No 'p14:creationId' tag found in ${slideRel.file}`);
          continue;
        }
  
        const creationIdSlide = creationIdItem.getAttribute('val');
  
        if (!creationIdSlide) {
          console.warn(`Attribute 'val' is undefined in ${slideRel.file}`);
          continue;
        }
  
        const elementIds = this.elementCreationIds(slideXml, archive);
        const slideInfo = await this.getSlideInfo(
          slideXml,
          archive,
          slideRel.file,
        );
  
        creationIds.push({
          id: Number(creationIdSlide),
          number: this.parseSlideRelFile(slideRel.file),
          elements: elementIds,
          info: slideInfo,
        });
      } catch (err) {
        console.error(`An error occurred while processing ${slideRel.file}:`, err);
      }
    }
  
    return creationIds.sort((slideA, slideB) => 
      slideA.number < slideB.number ? -1 : 1
    );
  }
```
Old error 
```js
 TypeError: Cannot read properties of undefined (reading 'getAttribute')

      33 |     const creationIds: SlideInfo[] = [];
      34 |     for (const slideRel of relationships) {
    > 35 |       const slideXml = await XmlHelper.getXmlFromArchive(
         |                     ^
      36 |         archive,
      37 |         'ppt/' + slideRel.file,
      38 |       );

      at XmlTemplateHelper.<anonymous> (src/helper/xml-template-helper.ts:35:21)
      at fulfilled (src/helper/xml-template-helper.ts:5:58)```
New Error 

```js
 console.warn
      No 'p14:creationId' tag found in slides/slide1.xml

      47 |   
      48 |         if (!creationIdItem) {
    > 49 |           console.warn(`No 'p14:creationId' tag found in ${slideRel.file}`);
         |                   ^
      50 |           continue;
      51 |         }
      52 |   
```

Repro steps. -- chuck in a getInfo or setCreationIds into the get-all-text-elements file

**Comment by singerla** [comment]
Hi @MP70 ! Thanks a lot for the efforts so far! I need to go deeper into this next week. Have a nice weekend! We'll proceed on Monday :wave:
